SU003-Create-API-repository
Criofann/JobForge-API pull request #5
Opened 2023-12-01 20:23 UTC by UserConor

- Added .gitignore file to prevent unwanted files appearing in the repository
- API skeleton created using Java and Dropwizard

<img width="439" alt="image" src="https://github.com/Criofann/JobForge-API/assets/145464062/9fffd49b-f50f-404c-9eb4-06952eb2c7ad">

2023-12-05 09:30 UTC, Joseph-Magee approved these changes
looks good

2023-12-05 14:24 UTC, lullabelle commented
Hi
Placeholder files probably not needed until ready to commit an actual file into those folders. Saves having to delete the placeholder later

Joanne

2023-12-05 14:25 UTC, jkelso662 requested changes
You have 2x placeholder RoleControllers - best at least sort that. Also just cautioning the placeholder.txt files as you will need to remove these as you use those folders. Otherwise looking good!

2023-12-05 14:25 UTC, jkelso662 commented on src/main/java/org/kainos/ea/db/RoleController.java
I think this is a duplication of src/main/java/org/kainos/ea/resources/RoleController.java. Presumably this would be a DAO but you aren't using it so best not create it yet.

2023-12-06 09:47 UTC, jkelso662 approved these changes
Nice! Very good. 
However some late night coding I see!!! 👀

2023-12-06 10:04 UTC, Joseph-Magee commented
doesn't meet ticket requirments

2023-12-06 11:29 UTC, Joseph-Magee approved these changes
looks good

2023-12-06 14:51 UTC, merged